# Generated by Django 5.1.3 on 2024-12-06 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='imagen',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='imagenes/'),
        ),
    ]
