# Generated by Django 5.1.3 on 2024-12-08 12:41

import curso.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("curso", "0003_alter_publicacion_duracion_like"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publicacion",
            name="imagen",
            field=models.ImageField(
                blank=True,
                max_length=200,
                null=True,
                upload_to=curso.models.unique_image_path,
            ),
        ),
    ]
